In [3]:
import pandas as pd

In [6]:
perguntas = pd.read_csv('stackoverflow_perguntas.csv')
perguntas.sample(10)

Perguntas         Tags
5173  Estou tendo alguns problemas com Passaport.js....      node.js
3267  Boa tarde galera,   Tem como criar uma variáve...      node.js
3426  Neste caso:  CODE   como saberei quando o cliq...       jquery
3964  Eu estava precisando carregar conteúdo sob dem...       jquery
173   View:  CODE     Controller:  CODE   Estou com ...      jquery 
512   Estou montando uma tabela de planos TABELA , e...         html
957   Para contextualizar: O código é uma página com...        html 
3571  Tenho meu bd, porém, está me trazendo um resul...        html 
1516  Estou com um problema no Scrollorama. Gostaria...  jquery html
5309  Boa tarde pessoal. Estou começando começando a...      angular

# Classificações:

## Binária: é quando apenas duas opcões, sendo uma ou a outra
## Multiclass: é quando tem várias opções, mas sendo apenas uma
## Multilabel: é quando tem várias opções e você pode ser mais de uma

In [14]:
len(perguntas)

5408

In [15]:
len(perguntas.Tags.unique())

37

In [13]:
perguntas.Tags.unique()

array(['node.js', 'jquery', 'html', 'html angular ', 'html ', 'angular',
       'angular ', 'jquery html  ', 'jquery ', 'jquery html',
       'jquery html ', 'html angular', 'angular node.js ', 'html  ',
       'jquery html angular', 'node.js ', 'html jquery', 'html jquery ',
       'jquery angular  ', 'html node.js', 'jquery  ', 'angular node.js',
       'jquery angular', 'html node.js ', 'jquery node.js ', 'angular  ',
       'jquery angular ', 'jquery html angular ', 'node.js html ',
       ' node.js', 'node.js html', 'html angular  ', 'jquery node.js',
       'angular html', 'html angular  node.js', 'jquery html node.js',
       'html angular node.js'], dtype=object)

In [16]:
'html' != 'html '

True

In [18]:
'html angular' != 'angular html'

True

In [20]:
# Ex:
'node.js html '.split()

['node.js', 'html']

In [27]:
lista_de_tags = list()
for tags in perguntas.Tags.unique():
    for tag in tags.split():
        if tag not in lista_de_tags:
            lista_de_tags.append(tag)

print(lista_de_tags)            

['node.js', 'jquery', 'html', 'angular']


In [26]:
node_js = list()
for linha_tag in perguntas.Tags:
    if 'node.js' in linha_tag:
        node_js.append(1)
    else:
        node_js.append(0)
        
 

In [25]:
perguntas['node.js'] = node_js
perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  
0           1  
1           1  
2           0  
3           0  
4           0  
...       ...  
5403        0  
5404        0  
5405        0  
5406        0  
5407        0  

[5408 rows x 3 columns]

In [33]:
def nova_coluna(lista_tag, dataframe, nome_tags):
    for tag in lista_tag:
        coluna = list()
        for linha_tag in dataframe[nome_tags]:
            if tag in linha_tag:
                coluna.append(1)      
            else:
                coluna.append(0)
        dataframe[tag] = coluna       

In [34]:
nova_coluna(lista_de_tags, perguntas, 'Tags')

In [36]:
perguntas.head(10)

Perguntas           Tags  node.js  \
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1   
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1   
2  Como inverter a ordem com que o jQuery itera u...         jquery        0   
3  Eu tenho uma página onde pretendo utilizar um ...           html        0   
4  Como exibir os dados retornados do FireStore e...  html angular         0   
5  Vi esse vídeo (link abaixo) e gostaria de cons...          html         0   
6  Eu consigo fazer uma requisição de upload de u...        angular        0   
7  Está apresentando o seguinte erro:  'ionic' nã...        node.js        1   
8  Tenho um formulário reativo e eu preciso mostr...        angular        0   
9  Eu estou com esse problema e não faço ideia de...        node.js        1   

   jquery  html  angular  
0       0     0        0  
1       0     0        0  
2       1     0        0  
3       0     1        0  
4       0     1        1  
5       0     1        0  
6       0     0        1  
7       0     0        0  
8       0     0        1  
9       0     0        0

In [40]:
# EX:
lista_1 = [1,2]
lista_2 = [5,4]
# 1,5      2,4

lista_zip = zip(lista_1, lista_2)
print(list(lista_zip))

[(1, 5), (2, 4)]


In [44]:
lista_zip_tags =list(zip(perguntas[lista_de_tags[0]],
                    perguntas[lista_de_tags[1]],
                    perguntas[lista_de_tags[2]],
                    perguntas[lista_de_tags[3]]))

perguntas['todas_tags'] = lista_zip_tags
perguntas.head()

Perguntas           Tags  node.js  \
0  Possuo um projeto Node.js porém preciso criar ...        node.js        1   
1  Gostaria de fazer testes unitários no Node.js,...        node.js        1   
2  Como inverter a ordem com que o jQuery itera u...         jquery        0   
3  Eu tenho uma página onde pretendo utilizar um ...           html        0   
4  Como exibir os dados retornados do FireStore e...  html angular         0   

   jquery  html  angular    todas_tags  
0       0     0        0  (1, 0, 0, 0)  
1       0     0        0  (1, 0, 0, 0)  
2       1     0        0  (0, 1, 0, 0)  
3       0     1        0  (0, 0, 1, 0)  
4       0     1        1  (0, 0, 1, 1)

In [46]:
from sklearn.model_selection import train_test_split 

# o segundo parametro vai ser uma coluna onde tem a resposta de todas os tipos, para que a amosta retirada possa ser semelhante ao todo

perguntas_treino, perguntas_teste ,tags_treino ,tags_teste = train_test_split(
    perguntas.Perguntas,
    perguntas.todas_tags,
    test_size = 0.2,
    random_state = 123
)


In [47]:
perguntas_treino

1577       array1 = [1,2,3];   array2 = ["um","dois","...
1927    Não sei se fui claro no título, mas quem é da ...
3409    Alguém sabe me dizer qual a melhor forma de re...
4606    Estou com problemas ao tentar validar campos d...
5237    Preciso copiar um valor de dentro de um CODE  ...
                              ...                        
5218    Tenho um sisteminha, para mudar o layout da pá...
4060    Como fazer alto scoll ao carregar a página?  E...
1346    Explicação:  Tenho uma CODE  pai que contém du...
3454    Estou querendo fazer um sistema onde eu iria t...
3582    Galera eu to com um problemão, ja pesquisei ba...
Name: Perguntas, Length: 4326, dtype: object

In [48]:
# Fazemos a vetorização,nas perguntas por serem string, levando em consideração se as palavras utilizadas foram por exemplo
# ótimo -> ter gostado do filme 
# péssimo -> não ter gostado do filme


In [53]:
from sklearn.feature_extraction.text import TfidfVectorizer

vetorizar = TfidfVectorizer(max_features = 5000, max_df = 0.85)
vetorizar

TfidfVectorizer(max_df=0.85, max_features=5000)

In [76]:
vetorizar.fit(perguntas.Perguntas)
perguntas_treino_tfidf = vetorizar.transform(perguntas_treino)
perguntas_teste_tfidf = vetorizar.transform(perguntas_teste) 

print(perguntas_treino_tfidf.shape)
print(perguntas_teste_tfidf.shape)

(4326, 5000)
(1082, 5000)


In [77]:
type(tags_treino)

pandas.core.series.Series

In [78]:
import  numpy as np

tags_treino_array = np.asarray(list(tags_treino))
tags_teste_array = np.asarray(list(tags_teste))

print(tags_treino_array)
print(type(tags_treino_array)) 

[[0 1 0 0]
 [0 1 0 0]
 [0 0 1 0]
 ...
 [0 1 1 0]
 [0 0 1 0]
 [0 1 1 0]]
<class 'numpy.ndarray'>


In [81]:
# apenas para ver o quão bom seria esse algoritmo

from sklearn.multiclass import OneVsRestClassifier
from sklearn.linear_model import LogisticRegression

regressao_logistica = LogisticRegression(solver = 'lbfgs')
classificador_onevsrest = OneVsRestClassifier(regressao_logistica)

classificador_onevsrest.fit(perguntas_treino_tfidf, tags_treino_array)

resultado_onevsrest = classificador_onevsrest.score(perguntas_test_tfidf, tags_teste_array)
print('Resultado {0: .2f}%'. format(resultado_onevsrest*100))

Resultado  41.68%


In [83]:
perguntas['todas_tags'].unique()

array([(1, 0, 0, 0), (0, 1, 0, 0), (0, 0, 1, 0), (0, 0, 1, 1),
       (0, 0, 0, 1), (0, 1, 1, 0), (1, 0, 0, 1), (0, 1, 1, 1),
       (0, 1, 0, 1), (1, 0, 1, 0), (1, 1, 0, 0), (1, 0, 1, 1),
       (1, 1, 1, 0)], dtype=object)

In [90]:
len(perguntas['todas_tags'].unique())

13

In [91]:
# Quando menor o Hamming Loss melhor diferença entre a Acurácia que quanto maior melhor

# Axurácia: 
    # Ela vê se acertou a linha toda, caso sim vai ser marcado um ponto
    # Ex: no exemplo abaixo acertou somente a primeira linha sendo 1 de 3 -> 1/3
# Hamming Loss:
    # Ela olha de um por um para vê se acertou ou não  
    # Ex: no exemplo a baixo ela errou apenas 3 de 12 -> 3/12     

<img width='700px' src = 'Imagens/ExemploRealEPrevisto.png'>

<img width='700px' src = 'Imagens/Resultados.png'>

In [94]:
from sklearn.metrics import hamming_loss

previsao_onevsrest = classificador_onevsrest.predict(perguntas_test_tfidf)
hamming_loss_onevsrest = hamming_loss(tags_teste_array, previsao_onevsrest)

print('Hamming Loss {0: .2f}'. format(hamming_loss_onevsrest))
# quanto menor melhor

Hamming Loss  0.19


In [95]:
perguntas

Perguntas           Tags  \
0     Possuo um projeto Node.js porém preciso criar ...        node.js   
1     Gostaria de fazer testes unitários no Node.js,...        node.js   
2     Como inverter a ordem com que o jQuery itera u...         jquery   
3     Eu tenho uma página onde pretendo utilizar um ...           html   
4     Como exibir os dados retornados do FireStore e...  html angular    
...                                                 ...            ...   
5403  Queria saber como pegar o total de cores de um...   jquery html    
5404  Boa noite, estou usando phonegap para fazer um...          html    
5405  Estou construindo um mini fórum, e nele, os us...    jquery html   
5406  Boa tarde,  Estou para desenvolver um site na ...           html   
5407  Estou fazendo um hotsite, ele é one page, e é ...    jquery html   

      node.js  jquery  html  angular    todas_tags  
0           1       0     0        0  (1, 0, 0, 0)  
1           1       0     0        0  (1, 0, 0, 0)  
2           0       1     0        0  (0, 1, 0, 0)  
3           0       0     1        0  (0, 0, 1, 0)  
4           0       0     1        1  (0, 0, 1, 1)  
...       ...     ...   ...      ...           ...  
5403        0       1     1        0  (0, 1, 1, 0)  
5404        0       0     1        0  (0, 0, 1, 0)  
5405        0       1     1        0  (0, 1, 1, 0)  
5406        0       0     1        0  (0, 0, 1, 0)  
5407        0       1     1        0  (0, 1, 1, 0)  

[5408 rows x 7 columns]

In [96]:
# correlação:
    # 1-> é perfeito
    # 0-> é ruim

perguntas.corr()

node.js    jquery      html   angular
node.js  1.000000 -0.321485 -0.273523 -0.101787
jquery  -0.321485  1.000000 -0.253977 -0.366269
html    -0.273523 -0.253977  1.000000 -0.286706
angular -0.101787 -0.366269 -0.286706  1.000000

In [99]:
pip install scikit-multilearn

     |████████████████████████████████| 89 kB 1.3 MB/s eta 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [101]:
from skmultilearn.problem_transform import ClassifierChain

In [103]:
# Essa maneira está fazendo com que a cada coluna que passa ele utilizar esse resultado, sendo em cadeia

classificador_cadeia = ClassifierChain(regressao_logistica)
classificador_cadeia.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_cadeia = classificador_cadeia.score(perguntas_test_tfidf, tags_teste_array)
print('Resultado {0: .2f}%'. format(resultado_cadeia*100))

previsao_cadeia = classificador_cadeia.predict(perguntas_test_tfidf)
hamming_loss_cadeia = hamming_loss(tags_teste_array, previsao_cadeia)
print('Hamming Loss {0: .2f}'. format(hamming_loss_cadeia))

Resultado  49.82%
Hamming Loss  0.21


In [104]:
# A escolha do algoritmo seria de acordo com seu objetivo

# Em relação ao algoritmo anterior, esse foi um pouco maior então seria um pouco pior
# Em relação a curásia: ta acertando mais linhas inteiras e errando alguns pontuais em relação a binaria

## Algoritmo adaptativos

In [111]:
from skmultilearn.problem_transform import BinaryRelevance


classificador_br = BinaryRelevance(regressao_logistica)
classificador_br.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_br = classificador_br.score(perguntas_test_tfidf, tags_teste_array)
print('Resultado {0: .2f}%'. format(resultado_br*100))

previsao_br = classificador_br.predict(perguntas_test_tfidf)
hamming_loss_br = hamming_loss(tags_teste_array, previsao_br)
print('Hamming Loss {0: .2f}'. format(hamming_loss_br))

Resultado  41.68%
Hamming Loss  0.19


In [123]:
from skmultilearn.adapt import MLkNN

classificador_mlknn = MLkNN()
classificador_mlknn.fit(perguntas_treino_tfidf, tags_treino_array)
resultado_mlknn = classificador_mlknn.score(perguntas_test_tfidf, tags_teste_array)
print('Resultado {0: .2f}%'. format(resultado_mlknn*100))

previsao_mlknn = classificador_mlknn.predict(perguntas_test_tfidf)
hamming_loss_mlknn = hamming_loss(tags_teste_array, previsao_mlknn)
print('Hamming Loss {0: .2f}'. format(hamming_loss_mlknn))

/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:68: FutureWarning: Pass n_neighbors=10 as keyword args. From version 0.25 passing these as positional arguments will result in an error
  warnings.warn("Pass {} as keyword args. From version 0.25 "


Resultado  32.35%
Hamming Loss  0.25


In [122]:
print('Hamming Loss cadeia {0: .2f}'. format(hamming_loss_cadeia))
print('Resultado cadeia {0: .2f}%'. format(resultado_cadeia*100))

Hamming Loss cadeia  0.21
Resultado cadeia  49.82%


In [124]:
print('Hamming Loss binaria {0: .2f}'. format(hamming_loss_br))
print('Resultado banaria {0: .2f}%'. format(resultado_br*100))

Hamming Loss binaria  0.19
Resultado banaria  41.68%


In [132]:
resultados_classificacao = pd.DataFrame()
resultados_classificacao['perguntas'] = perguntas_teste.values # values -> faz com que o indices fique inicie em 1
resultados_classificacao['tags real'] = list(tags_teste) # o list -> faz com que ele bote em ordem
resultados_classificacao['binaria'] = list(previsao_br.toarray())
resultados_classificacao['cadeia'] = list(previsao_cadeia.toarray())
resultados_classificacao['mlknn'] = list(previsao_mlknn.toarray())
resultados_classificacao

perguntas     tags real  \
0     estou com conflito entre o  CODE   e os  CODE ...  (0, 1, 0, 0)   
1     Estou fazendo um site que eu sou obrigado a us...  (0, 0, 1, 0)   
2     Recentemente fiz um refactor do meu código par...  (1, 0, 0, 0)   
3     Eu tenho esse código em CODE  que passo valore...  (0, 1, 1, 0)   
4     Olá, em minha função tem o evento CODE  que de...  (0, 1, 1, 0)   
...                                                 ...           ...   
1077  Estou a desenvolver um website em jQuery. E at...  (0, 1, 0, 0)   
1078  Estou usando este plugin - jquery autocomplete...  (0, 1, 0, 0)   
1079  Tenho o seguinte jQuery:  CODE   Nisto, quanti...  (0, 1, 0, 0)   
1080  Estou usando o SimpleModal Contact Form de Eri...  (0, 1, 0, 0)   
1081  Estou tento problemas com o webpack, gostaria ...  (0, 0, 0, 1)   

           binaria                cadeia         mlknn  
0     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 0, 0, 0]  
1     [0, 0, 1, 0]  [0.0, 0.0, 1.0, 0.0]  [0, 1, 1, 0]  
2     [1, 0, 0, 0]  [1.0, 0.0, 0.0, 0.0]  [1, 0, 0, 0]  
3     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 0, 1, 0]  
4     [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 0, 1, 0]  
...            ...                   ...           ...  
1077  [0, 1, 1, 0]  [0.0, 1.0, 1.0, 0.0]  [0, 0, 1, 0]  
1078  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1079  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1080  [0, 1, 0, 0]  [0.0, 1.0, 0.0, 0.0]  [0, 1, 0, 0]  
1081  [0, 0, 0, 0]  [0.0, 0.0, 1.0, 0.0]  [0, 0, 1, 0]  

[1082 rows x 5 columns]

In [133]:
resultados_classificacao.iloc[1]

perguntas    Estou fazendo um site que eu sou obrigado a us...
tags real                                         (0, 0, 1, 0)
binaria                                           [0, 0, 1, 0]
cadeia                                    [0.0, 0.0, 1.0, 0.0]
mlknn                                             [0, 1, 1, 0]
Name: 1, dtype: object

In [134]:
resultados_classificacao.perguntas[1]

'Estou fazendo um site que eu sou obrigado a usar HTML, CSS e JavaScript no máximo. Só que muitas coisas que eu preciso do PhP eu não posso usar. Sendo assim eu estive pesquisando por sinonimo de CODE  e encontrei o seguinte, que ajudou em partes:  CODE   Tá, mas qual é o problema? Ele cria uma barra de rolagem do lado. Eu sei como remover com CSS, mas o texto que foi inserido rola só dentro da área da CODE  e eu queria que fizesse como se o texto inserido fizesse parte da página, como funciona no CODE  do PhP. A questão é, como fazer a mecânica do JavaScript nesse caso ficar igual ao do PhP?  Print para exemplificar: https://imgur.com/a/V9AGLgB '